title: <p align="center"> Joanna Peck-Rashid </p>

logo: "/images/headshot_small.jpeg?raw=true" 

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/joannarashid/">LinkedIn</a> |
  <a href="https://github.com/joannarashid">GitHub</a>
  </p>
  Data Scientist and San Francisco Bay Area Native specializing in technical data analysis, visualization, statistical modeling, and machine learning in healthcare.
  <br><br>
  </p>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-PZHPNDQQN7 # Google Analytics tracking ID
